import type { PilotProfile } from "@/types/pilot";

/**
 * Drone Network — pilot data adapter.
 *
 * Today: returns mock pilots so we can build the UI without WordPress.
 * Tomorrow: swap the body of getPilots() for a fetch call to the WP REST endpoint.
 *
 * The mock and the API must return the SAME shape. The contract is in
 * src/types/pilot.ts. If you change the contract here, update the type and
 * notify whoever is building the WordPress side.
 */

const MOCK_PILOTS: PilotProfile[] = [
  {
    id: 1,
    slug: "aero-beauce",
    kind: "pilot",
    name: "Aéro Beauce",
    city: "Saint-Georges, QC",
    postal: "G5Y",
    province: "QC",
    lat: 46.1255,
    lng: -70.6647,
    description: {
      fr: "Spécialiste de l'épandage agricole par drone BVLOS dans la Beauce.",
      en: "BVLOS agricultural spraying specialist in Beauce.",
    },
    bio: {
      fr: "Relevés agricoles et cartographie de précision pour les fermes de la Beauce. Spécialisé en épandage par drone de classe 25 kg+.",
      en: "Precision agriculture surveys and mapping for Beauce farms. Specialized in 25 kg+ drone spraying.",
    },
    gallery: [],
    annees_experience: 7,
    langues: ["FR", "EN"],
    specs: ["agri-precision", "foresterie"],
    livrables: ["ortho", "carto-precision", "epandage"],
    payloads: ["multi", "sprayer", "rtk"],
    type_licence: "BVLOS",
    licence_file_url: "/mock/licence-aerobeauce.pdf",
    assurance: true,
    autres_certs: "Opérations à proximité de personnes (TC-OPP)",
    drones: ["DJI Agras T40", "DJI Mavic 3 Multispectral"],
    email: "contact@aerobeauce.ca",
    phone: "418 555-0142",
    site_web: "https://aerobeauce.ca",
    instagram: "aerobeauce",
    linkedin: "aero-beauce",
    avis_google_url: "https://www.google.com/maps/place/aero-beauce",
    plan_abonnement: "Pro",
    status: "Approuvé",
    badge_pro: true,
    date_inscription: "2026-06-01",
    pro: true,
    verified: true,
  },
  {
    id: 2,
    slug: "studio-vertige",
    kind: "pilot",
    name: "Studio Vertige",
    city: "Montréal, QC",
    postal: "H2X",
    province: "QC",
    lat: 45.5088,
    lng: -73.5878,
    description: {
      fr: "Cinéma et événementiel par drone à Montréal.",
      en: "Cinema and event drone work in Montréal.",
    },
    bio: {
      fr: "Prises de vue cinéma et captation d'événements. Drones FPV et grand format certifiés.",
      en: "Cinema aerials and event capture. FPV and large-format certified drones.",
    },
    gallery: [],
    annees_experience: 4,
    langues: ["FR", "EN"],
    specs: ["photo-video"],
    livrables: ["video", "photo"],
    payloads: ["rgb"],
    type_licence: "Avancée",
    licence_file_url: "/mock/licence-vertige.pdf",
    assurance: true,
    autres_certs: null,
    drones: ["DJI Inspire 3", "DJI Avata 2"],
    email: "alex@studiovertige.ca",
    phone: "514 555-0188",
    site_web: "https://studiovertige.ca",
    instagram: "studio.vertige",
    youtube: "studiovertige",
    avis_google_url: null,
    plan_abonnement: "Pro",
    status: "Approuvé",
    badge_pro: true,
    date_inscription: "2026-06-01",
    pro: true,
    verified: true,
  },
  {
    id: 3,
    slug: "nordvue-inspection",
    kind: "shop",
    name: "NordVue Inspection",
    city: "Québec, QC",
    postal: "G1K",
    province: "QC",
    adresse: "845 boul. Charest E, Québec, QC G1K 3J8",
    lat: 46.8139,
    lng: -71.208,
    description: {
      fr: "Inspection thermique et réparation DJI dans la grande région de Québec.",
      en: "Thermal inspection and DJI repair in Québec City area.",
    },
    bio: {
      fr: "Inspection thermique de toitures, ponts et lignes électriques. Service de réparation certifié DJI.",
      en: "Thermal inspection of roofs, bridges and power lines. DJI-certified repair service.",
    },
    gallery: [],
    annees_experience: 12,
    langues: ["FR", "EN"],
    services: ["reparation", "vente", "location"],
    marques: ["DJI", "Autel"],
    email: "info@nordvue.ca",
    phone: "418 555-0234",
    site_web: "https://nordvue.ca",
    linkedin: "nordvue-inspection",
    avis_google_url: "https://www.google.com/maps/place/nordvue",
    plan_abonnement: "Pro",
    status: "Approuvé",
    badge_pro: true,
    date_inscription: "2026-06-01",
    pro: false,
    verified: true,
  },
  {
    id: 4,
    slug: "ecole-altitude",
    kind: "school",
    name: "École Altitude",
    city: "Sherbrooke, QC",
    postal: "J1H",
    province: "QC",
    adresse: "2300 rue Belvédère N, Sherbrooke, QC J1H 4A5",
    lat: 45.4001,
    lng: -71.8825,
    description: {
      fr: "Formation RPAS bilingue à Sherbrooke, reconnue par Transports Canada.",
      en: "Bilingual TC-recognized RPAS training in Sherbrooke.",
    },
    bio: {
      fr: "Formation RPAS avancée et préparation à l'examen de Transports Canada. Cours bilingues.",
      en: "Advanced RPAS training and Transport Canada exam prep. Bilingual courses.",
    },
    gallery: [],
    annees_experience: 8,
    langues: ["FR", "EN"],
    formations: ["base", "avance", "examen"],
    formations_tc: true,
    email: "info@ecolealtitude.ca",
    phone: "819 555-0399",
    site_web: "https://ecolealtitude.ca",
    facebook: "ecolealtitude",
    avis_google_url: "https://www.google.com/maps/place/ecole-altitude",
    plan_abonnement: "Pro",
    status: "Approuvé",
    badge_pro: true,
    date_inscription: "2026-06-01",
    pro: false,
    verified: true,
  },
  {
    id: 5,
    slug: "prairie-sky-aerial",
    kind: "pilot",
    name: "Prairie Sky Aerial",
    city: "Winnipeg, MB",
    postal: "R3C",
    province: "MB",
    lat: 49.8954,
    lng: -97.1385,
    description: {
      fr: "Couverture agricole multispectrale dans les Prairies.",
      en: "Multispectral agricultural coverage across the Prairies.",
    },
    bio: {
      fr: "Couverture agricole des Prairies. Cartographie multispectrale et épandage de précision.",
      en: "Prairie crop coverage. Multispectral mapping and precision spraying.",
    },
    gallery: [],
    annees_experience: 6,
    langues: ["EN", "FR"],
    specs: ["agri-precision", "arpentage"],
    livrables: ["ortho", "carto-precision", "epandage", "topo"],
    payloads: ["multi", "sprayer"],
    type_licence: "Avancée",
    licence_file_url: "/mock/licence-prairiesky.pdf",
    assurance: true,
    autres_certs: null,
    drones: ["DJI Agras T30", "DJI Mavic 3M"],
    email: "pilot@prairiesky.ca",
    phone: "204 555-0512",
    site_web: "https://prairiesky.ca",
    linkedin: "prairie-sky-aerial",
    avis_google_url: null,
    plan_abonnement: "Pro",
    status: "Approuvé",
    badge_pro: true,
    date_inscription: "2026-06-01",
    pro: true,
    verified: true,
  },
  {
    id: 6,
    slug: "west-coast-drone-co",
    kind: "shop",
    name: "West Coast Drone Co.",
    city: "Vancouver, BC",
    postal: "V6B",
    province: "BC",
    adresse: "1280 W Cordova St, Vancouver, BC V6B 1A3",
    lat: 49.2827,
    lng: -123.1207,
    description: {
      fr: "Boutique de drones haut de gamme à Vancouver.",
      en: "Premium drone retailer in Vancouver.",
    },
    bio: {
      fr: "Boutique de drones haut de gamme et école de pilotage sur la côte ouest.",
      en: "Premium drone retailer and pilot school on the west coast.",
    },
    gallery: [],
    annees_experience: 15,
    langues: ["EN"],
    services: ["vente", "location", "formation"],
    marques: ["DJI", "Autel", "Skydio"],
    email: "hello@westcoastdrone.com",
    phone: "604 555-0721",
    site_web: "https://westcoastdrone.com",
    instagram: "westcoastdrone",
    avis_google_url: "https://www.google.com/maps/place/westcoast-drone",
    plan_abonnement: "Pro",
    status: "Approuvé",
    badge_pro: true,
    date_inscription: "2026-06-01",
    pro: false,
    verified: true,
  },
  {
    id: 7,
    slug: "capital-survey-uav",
    kind: "pilot",
    name: "Capital Survey UAV",
    city: "Ottawa, ON",
    postal: "K1P",
    province: "ON",
    lat: 45.4215,
    lng: -75.6972,
    description: {
      fr: "Instructeur RPAS, suivi de chantier et modélisation 3D à Ottawa.",
      en: "RPAS instructor, construction tracking and 3D modelling in Ottawa.",
    },
    bio: {
      fr: "Suivi de chantier, orthophotographie et modélisation 3D. Instructeur certifié, vols BVLOS sur permis.",
      en: "Construction progress tracking, orthophotography and 3D modelling. Certified instructor, BVLOS-authorized.",
    },
    gallery: [],
    annees_experience: 9,
    langues: ["EN", "FR"],
    specs: ["construction", "carto-3d", "flotte"],
    livrables: ["ortho", "modele3d", "chantier", "topo"],
    payloads: ["rgb", "lidar", "rtk"],
    type_licence: "Instructeur",
    licence_file_url: "/mock/licence-capital.pdf",
    assurance: true,
    autres_certs: "Opérations urbaines, vols de nuit",
    drones: ["DJI Matrice 350 RTK", "WingtraOne GEN II"],
    email: "ops@capitalsurvey.ca",
    phone: "613 555-0934",
    site_web: "https://capitalsurvey.ca",
    linkedin: "capital-survey-uav",
    avis_google_url: "https://www.google.com/maps/place/capital-survey",
    plan_abonnement: "Pro",
    status: "Approuvé",
    badge_pro: true,
    date_inscription: "2026-06-01",
    pro: true,
    verified: true,
  },
  {
    id: 8,
    slug: "maritime-aerial",
    kind: "pilot",
    name: "Maritime Aerial",
    city: "Halifax, NS",
    postal: "B3J",
    province: "NS",
    lat: 44.6488,
    lng: -63.5752,
    description: {
      fr: "Photographie aérienne récréative sur la côte est.",
      en: "Recreational aerial photography on the east coast.",
    },
    bio: {
      fr: "Photographie aérienne et vidéo récréative. Spécialisé en bord de mer et paysages côtiers.",
      en: "Recreational aerial photography and video. Specialized in waterfront and coastal landscapes.",
    },
    gallery: [],
    annees_experience: 5,
    langues: ["EN", "FR"],
    specs: ["securite", "photo-video"],
    livrables: ["video", "photo"],
    payloads: ["rgb", "thermal"],
    type_licence: "Base",
    licence_file_url: "/mock/licence-maritime.pdf",
    assurance: false,
    autres_certs: null,
    drones: ["DJI Mavic 3 Pro"],
    email: "aerial@maritime.ca",
    phone: "902 555-0445",
    avis_google_url: null,
    plan_abonnement: "Récréatif",
    status: "Approuvé",
    badge_pro: false,
    date_inscription: "2026-06-01",
    pro: false,
    verified: true,
  },
];

/**
 * Returns every approved + active pilot for the map.
 * Calls the WP REST endpoint in production; returns mocks in dev until WP is ready.
 */
export async function getPilots(): Promise<PilotProfile[]> {
  // TODO: when WordPress is ready, replace with:
  //   const res = await fetch(`${process.env.WP_API_URL}/dn/v1/pilots`, {
  //     next: { revalidate: 60 },
  //   });
  //   if (!res.ok) throw new Error(`WP /dn/v1/pilots returned ${res.status}`);
  //   return res.json();
  return MOCK_PILOTS;
}

/** Returns a single pilot by slug, or null if not found. */
export async function getPilotBySlug(slug: string): Promise<PilotProfile | null> {
  const pilots = await getPilots();
  return pilots.find((p) => p.slug === slug) ?? null;
}
